services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-local
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-time-zone=+09:00
      - --log-bin-trust-function-creators=1
    volumes:
      - mysql_data:/var/lib/mysql
      # 초기 스크립트가 필요하면 아래 폴더에 .sql/.sh 넣으세요
      # - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
